### PR TITLE
Updated numero2/contao-storelocator

### PR DESCRIPTION
**Pull request by bennyborn**

### CODE REVIEW

**Review by fritzmg — APPROVED** [review]

**Comment by Toflar** [comment]
@fritzmg could you try to fix the issues before merging? https://github.com/contao/package-metadata/pull/376/checks
Otherwise it always falls back on me and I have to fix them like I did on Monday: https://github.com/contao/package-metadata/commit/9032e8b32a16591ceea24c2bca0692a30e64ad3b

**Comment by fritzmg** [comment]
Hm, no issues where shown when I merged it, everything was green. Or is it now always green and I have to check it manually?

**Comment by Toflar** [comment]
It's always green because there's no warning option. It's not red anymore in order to ease contribution.

**Comment by fritzmg** [comment]
I see, then I misunderstood.

**Pull request merged**
