### PR TITLE
added contaobayern as vendor

### PR DESCRIPTION
**Pull request by hella-schu**
new vendor contaobayern with new bundle contao-nuligadata-bundle

### CODE REVIEW

**Comment by xchs** [comment]
Could you please also add the word `nuLiga` to the [default.txt whitelist](https://github.com/contao/package-metadata/blob/master/linter/whitelists/default.txt)? Thanks.

**Comment by xchs** [comment]
`nuLiga` is the right spelling!

**Comment by hella-schu** [comment]
> 
> 
> Could you please also add the word `nuLiga` to the [default.txt whitelist](https://github.com/contao/package-metadata/blob/master/linter/whitelists/default.txt)? Thanks.

done

**Comment by xchs** [comment]
> done

Did you commit your changes to the whitelist file?

**Comment by hella-schu** [comment]
> 
> 
> > done
> 
> Did you commit your changes to the whitelist file?

now its done.

**Comment by xchs** [comment]
`nuLiga` is a **proper name**, so you should add this (as already mentioned above) in the `default.txt` whitelist and not in `de.txt` and `en.txt` whitelists.

**Comment by xchs** [comment]
`Spieldaten` could be added to the `de.txt` whitelist.

**Comment by xchs** [comment]
Thank you @hella-schu

**Pull request merged**
