### PR TITLE
change in the description and added some new keywords 

### PR DESCRIPTION
**Pull request by skynetindia**

### CODE REVIEW

**Comment by xchs** [comment]
@skynetindia Why did you put all the abbreviations in the English allowlist list, too?
https://github.com/contao/package-metadata/blob/c0e75866844bc55606bb1e05f4763bdfe7dee0eb/linter/allowlists/en.txt#L180-L189

It should be sufficient if these shortcuts are all already inserted in the default allowlist.

**Comment by skynetindia** [comment]
We have removed unwanted text from the en.txt file please check and let us know if anything else required

**Review by xchs — APPROVED** [review]

**Comment by skynetindia** [comment]
@xchs can you please merge the code as its not merge yet and showing us resolve conflict

**Comment by xchs** [comment]
@skynetindia Did you made your changes to the most current main branch?

**Comment by skynetindia** [comment]
Yes

**Comment by fritzmg** [comment]
The conflicts first need to be resolved (locally). Likely due to this PR https://github.com/contao/package-metadata/pull/503

**Comment by xchs** [comment]
> Likely due to this PR #503

Not likely. This problem was also present before the mentioned PR was merged.

image

**Comment by Toflar** [comment]
No idea but you can still merge it as long as you ensure the tests pass :)

**Comment by xchs** [comment]
> The conflicts first need to be resolved (locally)
@skynetindia Have you tried this yet?

**Pull request closed without merging**
