### PR TITLE
Added new bundles

### PR DESCRIPTION
**Pull request by w3scout**
Thanks for your help on the last PR. Somehow it wasn´t my day yesterday. ;-)

### CODE REVIEW

**Comment by Toflar** [comment]
No problem! :) Thanks for all the meta data 😎

**Comment by aschempp** [comment]
@w3scout did you remove this bundle from packagist/GitHub? Should we remove it from the extension list as well?

**Comment by w3scout** [comment]
@aschempp which bundle do you mean?

**Comment by aschempp** [comment]
the `w3scout/contao-addresses-bundle` which was added in this PR 😉

**Comment by aschempp** [comment]
Also noticed there are several other bundles gone from `w3scout` and `inszenium` (I don't know if that's you, could just be a coincidence?)

**Comment by w3scout** [comment]
> Also noticed there are several other bundles gone from `w3scout` and `inszenium` (I don't know if that's you, could just be a coincidence?)

I´ve updated my bundles. See: https://github.com/contao/package-metadata/pull/565

"inszenium"? Must be a coincidence.

**Comment by aschempp** [comment]
thank you! ❤️

**Pull request merged**
