### PR TITLE
Add vendor bugbuster

### PR DESCRIPTION
**Pull request by BugBuster1701**

### CODE REVIEW

**Comment by xchs** [comment]
I wonder why the logo is not visible in Chrome. In Firefox, the logo is displayed correctly.

https://github.com/contao/package-metadata/blob/1f176cbb0ec7e052f0e2e7d3fa4bc7f61db4786d/meta/bugbuster/logo.svg

contao manager 1 1 0

**Comment by ausi** [comment]
According to StackOverflow changing `xlink:href="data:img/png;base64,` to `xlink:href="data:image/png;base64,` should fix the problem.

**Comment by Toflar** [comment]
We'll see https://github.com/contao/package-metadata/commit/17286ee5878b1686305622aa75bee915ae7fc307

**Comment by Toflar** [comment]
Fixed, thx @ausi

**Comment by BugBuster1701** [comment]
Many Thanks.

**Pull request merged**
