### PR TITLE
Add packages of eikona-media

### PR DESCRIPTION
**Pull request by rabauss**
add [eikona-media/contao-system-information](https://packagist.org/packages/eikona-media/contao-system-information) + [eikona-media/contao-password-policy](https://packagist.org/packages/eikona-media/contao-password-policy)

### CODE REVIEW

**Comment by xchs** [comment]
The build process failed due to some words not passing the spell checker (see https://travis-ci.org/contao/package-metadata/builds/630033793#L398-L425). Please fix this and add the relevant words to the whitelists.

**Comment by Toflar** [comment]
I'll check the failing builds and fix them right away.

**Comment by rabauss** [comment]
You're to fast ;-)
Now, I just wanted to add the current codeowners `/meta/eikona-media/ @rabauss @devtty80`

Unfortunately, this spell checker is a little annoying if you're not familiar with the workflow.

**Comment by Toflar** [comment]
That's the purpose of a spell checker. It has to be annoying :) 
You can run it locally too. Anyway, let me fix the current master branch, then you can rebase and finish https://github.com/contao/package-metadata/pull/185.

**Pull request merged**
