### PR TITLE
Added some more dependencies

### PR DESCRIPTION
**Pull request by aschempp**

### CODE REVIEW

**Comment by fritzmg** [comment]
I am not sure this whole 'hiding "dependencies"' is such a good idea. There are some extensions marked as "dependency" which are easy to use with simple DCA changes even for not so advanced users. And they are wondering why all of a sudden extensions like the MulitColumnWizard has vanished.

**Comment by aschempp** [comment]
How can one write ever so simple DCA but not manually add an extension to the composer.json?

**Comment by fritzmg** [comment]
How to write a DCA adjustment is well documented and a lot of people made simple DCA adjustments simce forever, without having to know anything else about the Contao Framework or Composer.

**Comment by richardhj** [comment]
I guess people should always consult the README of an extension (at least this is what I do every time when I want to get to know, how to configure the MCW).
Consequently, the installation should be described in the README. I guess, the [MCW is doing it right](https://github.com/menatwork/contao-multicolumnwizard-bundle#install).

**Comment by fritzmg** [comment]
Well the README of the MCW specifically mentions searching for the extension in the Contao Manager - which is now not possible anymore ;).

**Comment by dmolineus** [comment]
For me there are 3 use cases where it would be useful if dependent extensions could be installed:

1. As part of the application as mentioned by @fritzmg  (I can follow arguments against this use case partially)
2. Third party dependencies which does not fullfill the minimum stability. For example, synccto is available as 4.0.0-betaX and depends on ctocommunication which would probably marked as `dependency` and not visible in the list. However, it's a beta version as well, so I have to install it first (or adjust the global minimum stability settings which is imho a bad practise). A end user wouldn't be able to do it.
3. Sometimes some extensions have bugs oder some alternate packages which should be used. So it might be possible to install a specific version of a dependency to get an extension temporary in a working state Both happend with the mcw before.

**Comment by aschempp** [comment]
> 1. As part of the application as mentioned by @fritzmg  (I can follow arguments against this use case partially)

I agree this makes sense, but again, if you're a developer/able to write/copy-paste PHP code, shouldn't you be able to add extensions in the composer.json? Someone needs to tell you which extension name anyway, so you already have that information?

> 2. Third party dependencies which does not fullfill the minimum stability. For example, synccto is available as 4.0.0-betaX and depends on ctocommunication which would probably marked as `dependency` and not visible in the list. However, it's a beta version as well, so I have to install it first (or adjust the global minimum stability settings which is imho a bad practise). A end user wouldn't be able to do it.

I just don't see this as a use-case for the Manager. Installing beta versions is not something a regular user should do. And any beta team or "please test this blog post" can point out how to add that to the composer.json, no?

> 3. Sometimes some extensions have bugs oder some alternate packages which should be used. So it might be possible to install a specific version of a dependency to get an extension temporary in a working state Both happend with the mcw before.

I fear people would never "revert" that change, but yeah that happens.

---

In any case, I agree it's currently not perfect, but we're trying to find a balance between *working automatically* and giving pro-users enough power. Maybe we should discuss this in the next public call?

**Comment by fritzmg** [comment]
> Maybe we should discuss this in the next public call?

👍 

> In any case, I agree it's currently not perfect, but we're trying to find a balance between _working automatically_ and giving pro-users enough power.

Imho, a nice-to-have would be a "quick dependency check" on the `contao/core-bundle` of each Contao package, so that the Contao Manager can automatically set the appropriate version requirement - or even branch. This could solve https://github.com/contao/contao-manager/issues/485#issuecomment-555221595

**Comment by aschempp** [comment]
As discussed on Mumble on the 29.11.2019 everyone agreed that we don't want regular users to advanced stuff in the Manager.

Regarding my comment in https://github.com/contao/package-metadata/pull/129#issuecomment-555366813

1. > As part of the application

    Developers should require their dependencies in the `composer.json` manually. The dependencies can still be updated through the Contao Manager.

2. > Third party dependencies which does not fullfill the minimum stability.

    I still don't see this as a use-case for the Manager.

3. > Sometimes some extensions have bugs oder some alternate packages which should be used. 

    Again, this is something that _can_ be done in the `composer.json`. Its something only a pro can do, because one would need to know the details.


For any further discussion, please open a new issue, as this is a PR that has already been merged.

**Pull request merged**
