### PR TITLE
Add vendor wangaz

### PR DESCRIPTION
**Pull request by 7FyOh**

### CODE REVIEW

**Comment by Toflar** [comment]
Thanks for the PR, the logo looks broken though? And once it's fixed, could you optimize it using a tool like https://jakearchibald.github.io/svgomg/ please? :)

**Comment by 7FyOh** [comment]
Sure, we have optimized the logo but are still trying to figure out, why GitHub cannot show it.

**Comment by Toflar** [comment]
I can merge it and we can see if everything works fine but I think if there's an issue displaying it on GitHub there's something wrong in general :)

**Comment by 7FyOh** [comment]
Thanks, we will stay tuned to fix the issue.

**Comment by xchs** [comment]
I can see the preview of the logo on GitHub:

svg_logo

**Comment by 7FyOh** [comment]
Now it is working in my browser as well 👍

**Pull request merged**
