### PR TITLE
Update netzhirsch/cookie-opt-in-bundle

### PR DESCRIPTION
**Pull request by Netzhirsch**

### CODE REVIEW

**Comment by fritzmg** [comment]
Don't you want to update `en.yml` too?

**Comment by Netzhirsch** [comment]
yeah, did it.

There are some questions left: 
- Where can I define the "from Netzhirsch" Link in the package manager?
- Where can I define the "Projectwebsite" Link in the package manager?

Thank You!

**Comment by aschempp** [comment]
> Where can I define the "from Netzhirsch" Link in the package manager?

That's the `author` property of your `composer.json`. I don't think you can configure that per language (yet).

> Where can I define the "Projectwebsite" Link in the package manager?

That's the homepage property of your `composer.json`. It **can** be set in the metadata repository if necessary per language as far as I know.

**Comment by Netzhirsch** [comment]
I think that is not working. Our composer.json looks like this:

> {
    ...
	"homepage": "https://www.netzhirsch.de/contao-cookie-opt-in-bundle.html",
	"license": "LGPL-3.0-or-later",
	"authors": [
		{
			"name": "Netzhirsch",
			"homepage": "https://www.netzhirsch.de"
		}
	],
	...
}

**Comment by fritzmg** [comment]
Seems like it's actually using the `homepage` of the first `author`?

**Comment by Netzhirsch** [comment]
yes, looks like this.

**Comment by Netzhirsch** [comment]
Oh, I think the changes are not merged yet.
When can we expect the merge?

**Comment by xchs** [comment]
Thank you @Netzhirsch

**Pull request merged**
