### PR TITLE
Whitelist Cleanup Part 2

### PR DESCRIPTION
**Pull request by bezin**
While we are at it, I cleaned out every term that is not needed in order to pass the linting. This reduces the Czech whitelist to one line and the English file to ~15%.

I fixed some errors a long the way as well and moved some more brand names to default.txt ;-)

### CODE REVIEW

**Comment by dmolineus** [comment]
Sorry @bezin, I just noticed your PR here after I published #79 which do some auto whitelist sanitizing. Hope both PRs could improve the metadata.

**Comment by Toflar** [comment]
Cool guys! Shall I merge the PR by @dmolineus first because it cleans up duplicates and then @bezin can rebase which should make the PR here a lot easier to read? What do you prefer?

**Comment by dmolineus** [comment]
Sounds reasonable so I'm fine with that way. Wdyt @bezin?

**Comment by bezin** [comment]
Yep, go for it.

**Comment by Toflar** [comment]
Done :)

**Comment by bezin** [comment]
Closed in favor of #80

**Pull request closed without merging**
