### PR TITLE
add form hint

### PR DESCRIPTION
**Pull request by zonky2**
add form hint

### CODE REVIEW

**Comment by fritzmg** [comment]
I think this shoul also be changed in the English version? /cc @bennyborn

**Comment by bennyborn** [comment]
> I think this should also be changed in the English version? /cc @bennyborn

That would be great. Could you add this @zonky2 ?

**Comment by bennyborn** [comment]
@zonky2 What? I thought "why not" if you're already on it. Otherwise I'll add it later, no problem.

**Review by xchs — APPROVED** [review]

**Comment by bennyborn** [comment]
Thanks @xchs !

**Pull request merged**
