### PR TITLE
Add meta data for cowegis/contao-geocoder

### PR DESCRIPTION
**Pull request by dmolineus**

### CODE REVIEW

**Comment by Toflar** [comment]
If it's the foundation for other extensions it means it cannot be used stand alone, right? So it will always be a dependency of any other bundle. Why would you ever search and install this then?

**Comment by dmolineus** [comment]
It's basically made for other extensions, but will be usable via an API endpoint. So you might want use it within your application with some custom javascript.

> Why would you ever search and install this then?

It's available in the search result as it's a contao bundle. So it's found anyway. The metadata description shows possible applications.

**Comment by aschempp** [comment]
If a user never has to manually install this (because it is a requirement of other extensions), then this should be a `type: library` or `type: symfony-bundle` and not a `contao-bundle`. If the package does not add features to Contao, but provides files for other packages, it's not a `contao-bundle`. FYI you can still use a manager plugin etc. in such packages.

**Comment by dmolineus** [comment]
>  If the package does not add features to Contao, but provides files for other packages, it's not a contao-bundle

It **does** add features to Contao as it provides a backend configuration. Type `library` or `symfony-bundle` would pretend it's a common symfony-bundle, which isn't the case here. 

So I don't really see the point of this conversation here.

**Comment by Toflar** [comment]
> So I don't really see the point of this conversation here.

Then the description is misleading. It says it only provides functionality for other extensions. If that's the case, it must not be a `contao-bundle`. But apparently that's not the case so the description should be adjusted which is why I asked in the first place 😄

**Comment by aschempp** [comment]
> So I don't really see the point of this conversation here.

Sorry to bother you, we're just trying to figure out the best approach here 😄 

> It does add features to Contao as it provides a backend configuration. Type library or symfony-bundle would pretend it's a common symfony-bundle, which isn't the case here.

You're right. Should we start using a type `contao-library` then? The type is totally irrelevant to Composer (apart from the `composer-plugin`). The point would only be to not show up in search results. Or do you think it's useful to a user to find the package at all?

**Comment by Toflar** [comment]
Ping @dmolineus

**Comment by dmolineus** [comment]
Improved the description

**Pull request merged**
