### PR TITLE
rel canonical logo

### PR DESCRIPTION
**Pull request by christianbarkowsky**

### CODE REVIEW

**Comment by aschempp** [comment]
da scheint noch etwas viel Leerraum?

**Comment by FannyWolff** [comment]
@aschempp Die Logos unterscheiden sich vom Aufbau nicht. Vielleicht magst du nochmal genauer definieren, was du mit Leerraum meinst?

**Comment by fritzmg** [comment]
@FannyWolff @christianbarkowsky 

image

**Comment by fritzmg** [comment]
This is actually an error in Github's SVG preview. The SVG itself is fine.

However, the SVG is not fully square. Its dimensions are 2335.5 by 2294.9 px.

**Comment by ausi** [comment]
> This is actually an error in Github's SVG preview. The SVG itself is fine.

Probably related to the `width="100%" height="100%"` which should be removed I think.

**Comment by aschempp** [comment]
it actually looks different in my Github viewer 😂 
Bildschirmfoto 2023-08-11 um 10 24 07

**Review by fritzmg — APPROVED** [review]

**Pull request merged**
