### PR TITLE
add new bundle alleaktien-quantitativ

### PR DESCRIPTION
**Pull request by cmette**

### CODE REVIEW

**Comment by MDevster** [comment]
@Toflar this is not a private repo, why the property homepage is required?

**Comment by fritzmg** [comment]
The package is not available in the public packagist: https://packagist.org/?query=pdir%2Falleaktien-quantitativ-bundle

**Comment by fritzmg** [comment]
There is however a [pdir/contao-alleaktien-quantitativ-bundle](https://packagist.org/packages/pdir/contao-alleaktien-quantitativ-bundle) package. If this is the correct package, then either the PR or the package name needs to be changed.

**Comment by MDevster** [comment]
@cmette please change bundle name ;)

**Review by MDevster — APPROVED** [review]

**Review by fritzmg — APPROVED** [review]

**Review by fritzmg — APPROVED** [review]

**Review by aschempp — APPROVED** [review]

**Pull request merged**
