### PR TITLE
Removed all .yml files, just trying to add logo

### PR DESCRIPTION
**Pull request by bright-cloud-studio**
I don't get what exactly was wrong with my file. I decided to just remove them all and try and add a base logo, as each package will have its own logo anyway but I was still getting failed for the file I had removed. Maybe I am not using github correctly, just trying to run it again hopefully this will ignore the file that no longer exists.

### CODE REVIEW

**Comment by bright-cloud-studio** [comment]
Seems it REALLY wants me to have these files now. It said it failed because of the Description spell check? I just wrote a different description and straight up copied the verified and accepted .yml file from the other package.

**Comment by bright-cloud-studio** [comment]
Ah I see, the work "hotspot" was killing it, I added it to the "allowlist" folder.

**Review by bright-cloud-studio — COMMENTED** [review]
Adding the work "hotspot" that stopped my validation

**Review by bright-cloud-studio — COMMENTED** [review]
I am so frustrated with this. I downloaded somebody elses file and just updated the values. I have now added a blank newline at the end of the file

**Comment by bright-cloud-studio** [comment]
FINALLY! I am new to github and this part of Contao and I am finally getting things working around here.

**Comment by xchs** [comment]
Well done. Everything good now. Add me as a reviewer and I'll approve and merge your PR.

**Review by xchs — APPROVED** [review]

**Comment by bright-cloud-studio** [comment]
Awesome! Never contributed to a project on github before, exciting. Thanks so much.

**Comment by xchs** [comment]
https://extensions.contao.org/?q=bright-cloud-studio

**Comment by bright-cloud-studio** [comment]
> https://extensions.contao.org/?q=bright-cloud-studio

Very cool! Going to finish rebranding the other packages so everything is up and looking sexy. Got my forum account approved too, today was a good day.

**Pull request merged**
