### PR TITLE
Added translations and logo for contao-twitterreader

### PR DESCRIPTION
**Pull request by hschottm**

### CODE REVIEW

**Comment by danielx11** [comment]
In my opinion, it is not allowed. You can´t use a logo for such a thing due to the idea, the developer is not twitter. On the other hand, you could try getting approval for playing safe.

**Comment by Ynda** [comment]
Have a look here: https://developer.twitter.com/en/developer-terms/display-requirements.html
The requirements for using the logo are explained here.

**Comment by hschottm** [comment]
Exchanged logo and added additional descriptions for other packages

**Comment by hschottm** [comment]
Close it

**Comment by frontendschlampe** [comment]
Hey @hschottm you have to wait, until we merge your pull request, before closing it and deleting your fork. Otherwise we can't merge any information.

**Pull request closed without merging**
