### PR TITLE
Linter: Support the "suggest" metadata

### PR DESCRIPTION
**Pull request by richardhj**
Add "suggest" to linter schema.

### CODE REVIEW

**Comment by aschempp** [comment]
Can you fix the merge conflicts please? Also, can we specify what keys the object can contain? I know Composer does that in their schema, but thats for JSON 🤔

**Comment by richardhj** [comment]
> Also, can we specify what keys the object can contain? I know Composer does that in their schema, but thats for JSON 🤔

Every key is allowed, no? Like `petschko/dhl-php-sdk` is an allowed key, how do you validate this?

**Comment by aschempp** [comment]
I meant that the object values must be strings. The key is always an unknown string, sorry about that 😊

**Comment by richardhj** [comment]
bf3475a4bd0fad11ee4611225d83e68314af4f38 should do it.
I tested it, and if you are for example are using an array without key-value-structure, the linter terminates with "[ERROR] Array value found, but an object is required [suggest]"

**Pull request merged**
