### PR TITLE
Add duncrow-gmbh/flipbert

### PR DESCRIPTION
**Pull request by cmartin6**
And remove all other duncrow-gmbh packages ;-)

### CODE REVIEW

**Comment by cmartin6** [comment]
Is this PR going to get merged or not? why is this still open?

**Comment by fritzmg** [comment]
Hm, I think the current implementation of the Linter is unable to deal with the removal of packages.

@cmartin6 may I ask, why did you remove these packages from Packagist in the first place?

**Comment by cmartin6** [comment]
@fritzmg I removed the packages because there are obsolete... We developed newer versions but didn't publish them yet.

**Comment by fritzmg** [comment]
It is unusual to simply delete Open Source packages, especially ones that might be defined as a dependency somewhere. The preferred way is to mark them as "abandoned" on Packagist instead. But since you are working on newer versions of these packages anyway, there was no need to do anything.

**Comment by cmartin6** [comment]
@fritzmg okay. Nevertheless I would like to add the duncrow-gmbh/flipbert package to the metadata-repo. Could you please merge my changes?

**Review by fritzmg — APPROVED** [review]

**Comment by fritzmg** [comment]
Done. Feel free to add the English language at a later time.

**Comment by cmartin6** [comment]
@fritzmg Thank you very much. But i still have one more question: why is the title and the description not loaded for duncrow-gmbh/flipbert? (see extensions.contao.org)

**Comment by xchs** [comment]
You have named the file `de.yaml` instead of `de.yml`.

**Comment by fritzmg** [comment]
@aschempp since the Linter supports both, shouldn't the meta package index support it as well? Or should the Linter be changed, so that it validates against at least one `.yml` (not `.yaml`) file being present?

**Comment by aschempp** [comment]
I think we should stick with one file extension. Allowing both might mean there  can be a `de.yml` **AND** `de.yaml` in the same directory. I'm fine with using `.yaml`  as well (and just rename everything), not sure what's the recommended one?

**Pull request merged**
