### PR TITLE
Remove superfluous words from the English allow list

### PR DESCRIPTION
**Pull request by fritzmg**
This cleans up the English allow list a bit.

### CODE REVIEW

**Comment by fritzmg** [comment]
@Total-Reality feel free to create a separate PR for that.

**Comment by Total-Reality** [comment]
> @Total-Reality feel free to create a separate PR for that.

Okay, thank you. I will create one as soon as the lint action (bug?) is fixed #414

**Review by xchs — APPROVED** [review]

**Comment by xchs** [comment]
What's the problem with the linter?

**Comment by fritzmg** [comment]
Unknown, see #414

**Comment by Total-Reality** [comment]
Is it possible that this problem occurs because you removed words that are not in the dictionary but used by at least one extension?

**Comment by fritzmg** [comment]
That would be identified by the action itself. But the action is not running for some reason.

**Comment by aschempp** [comment]
@fritzmg are you going to finish this PR? 😊

**Comment by fritzmg** [comment]
It was already finished, I just could not figure out what the problem with the linter was. I will update the PR again.

**Comment by fritzmg** [comment]
@aschempp since the linter does not run automatically I unfortunately have currently no way to test the changes. Someone would need to test it in their local environment.

**Comment by aschempp** [comment]
> Someone would need to test it in their local environment.

Could that someone be you? 🙃 
What would happen if a word is missing in the dictionary? Would the next PR fail or would indexing fail forever?

**Comment by fritzmg** [comment]
> Could that someone be you? 🙃

I could, but I would need to update my WSL setup. Someone already on a Unix system might have an easier time though.

> What would happen if a word is missing in the dictionary? Would the next PR fail or would indexing fail forever? 

I don't know, didn't you build the Indexing? ;) 
My assumption is that the linter is only used for PRs.

**Comment by aschempp** [comment]
@fritzmg I would suggest to merge this as-is and check if it works. There's apparently a cronjob to check the files every month (https://github.com/contao/package-metadata/actions/runs/3219322454/jobs/5264551105) but not sure if that is taken care of anyway 🙈

**Comment by fritzmg** [comment]
Yes, I think this can be merged as is. If a word is missing, it will show up in subsequent meta data PRs anyway.

**Review by aschempp — APPROVED** [review]

**Pull request merged**
