### PR TITLE
 Add wangaz/i18n-duplication-bundle 

### PR DESCRIPTION
**Pull request by 7FyOh**

### CODE REVIEW

**Comment by 7FyOh** [comment]
bildschirmfoto 2018-12-04 um 16 33 08
I thought, I should be able to approve the pull reqeust by myself – what am I doing wrong?

**Comment by ausi** [comment]
You cannot approve your own pull request. That’s just not how code reviews work 🙃

**Comment by 7FyOh** [comment]
Okay, then I missunderstood the documentation: 

> the Pull Request is merged and from now on you can approve Pull Requests that affect your own paths yourself.

**Comment by Toflar** [comment]
This is currently not supported. I'll update the docs.

**Pull request merged**
