### PR TITLE
add fritzmg, inspiredminds and fritzmg/contao-short-urls

### PR DESCRIPTION
**Pull request by fritzmg**

### CODE REVIEW

**Comment by fritzmg** [comment]
Hm... the spellcheck complains about words in the title. However, shouldn't only the description be checked? Titles of extensions could contain all sorts of "unknown" words.

Also it complains about invalid yaml data for the german translation. However, I am not sure what's wrong. The yaml should validate.

**Comment by Toflar** [comment]
> Also it complains about invalid yaml data for the german translation. However, I am not sure what's wrong. The yaml should validate.

Well, the `title` contains invalid data so the YAML is invalid :)
Just add `Short` to the spellchecker sources.

**Comment by fritzmg** [comment]
Right :). I have added it to the German whitelist.

**Comment by fritzmg** [comment]
Btw. how long does it take for any changes to be visible in the Contao Manager? Is there any (local) caching involved?

**Comment by Toflar** [comment]
The package indexer runs every 30 minutes.

**Pull request merged**
