### PR TITLE
Feature/plenta

### PR DESCRIPTION
**Pull request by christianbarkowsky**
Add contao-testimonials-bundle

### CODE REVIEW

**Comment by xchs** [comment]
Could you possibly add that to the whitelist, too?

image

**Comment by christianbarkowsky** [comment]
Me @xchs?

**Comment by xchs** [comment]
> Me @xchs?

Yup.

**Comment by christianbarkowsky** [comment]
Done @xchs

**Comment by xchs** [comment]
@christianbarkowsky Oh, you misunderstood the error message. This is not about "title", but about "**Testimonials**". :)

**Comment by christianbarkowsky** [comment]
I think I need a break. :)

**Review by xchs — APPROVED** [review]

**Comment by xchs** [comment]
Well done. Now you can take the break :)

Thank you.

**Pull request merged**
