### PR TITLE
Hopefully without a typo now

### PR DESCRIPTION
**Pull request by dalley-it**
Thanx for checking!

### CODE REVIEW

**Comment by dalley-it** [comment]
Travis Check has failed again, because of the words 'Dalley' and 'PhotoSwipe' within the title. I don't know how to update the whitelist as proposed by the check. Any help?!

**Comment by aschempp** [comment]
No worries. First of all, you don't need to close a pull request if you have more changes. Simply add them to the same branch. To fix the current issues, try the following:
 - Go to your fork (https://github.com/dalley-it/package-metadata)
 - Go to the `linter/whitelist` folder
 - Open the file for the desired language. Or in this case, these two words should be in the `defaults.txt`, which applies for all languages.
 - Once you have the file open, click on the pencil icon in the top right corner
 - Add the words to the list and save your changes

The new changes should automatically appear here on this pull request.

**Comment by dalley-it** [comment]
Hi Andreas,

thank you for your helpfull instructions. That worked flawless!

**Comment by Toflar** [comment]
Thank you! Index is updated every 30 minutes, so give it a little time until you check how it looks like in the Manager :)

**Pull request merged**
