### PR TITLE
Add metadata for gutesio bundles and con4gis/framework

### PR DESCRIPTION
**Pull request by coastforge-cro**
Adds the metadata for the new gutesio/data-model, gutesio/operator and con4gis/framework bundles.

### CODE REVIEW

**Comment by coastforge-cro** [comment]
I guess the check failed, because the packages were not yet accessible via packagist.org. But they are now. Is there any way to re-run the check manually?

**Comment by fritzmg** [comment]
May be with a `git push … --force`.

**Comment by aschempp** [comment]
Are the changes in con4gis-Framework related to this PR? Also, is con4gis-Framework "useful" for installation or rather a development component for other extensions?

**Comment by coastforge-cro** [comment]
What do you exactly mean with "related to this PR"? con4gis/framework and the other two bundles are all newly released, so the files for all three bundles are new.

It is mainly a development component that can be used to build other extensions/modules.

**Comment by coastforge-mei** [comment]
Please unlock the metadata for our new bundles. Thanks.

**Comment by fritzmg** [comment]
@coastforge-mei @costforge-cro I think the point of aschempp's question was to determine whether you want to define some of your packages as "dependencies". This way they would not be discoverable via the Contao Manager (or https://extensions.contao.org).

**Comment by aschempp** [comment]
yes, sorry for the late response. If the packages are dev components for other packages, it most likely does not make sense to show them in search results (but they sure can/should have a full description!). That's what the `dependency` flag is for, if you might add that? https://github.com/contao/package-metadata/blob/main/docs/de/README.md#yaml-syntax

**Review by fritzmg — APPROVED** [review]

**Review by aschempp — APPROVED** [review]

**Pull request merged**
