### PR TITLE
Add contao-themes-net/font-awesome-inserttag-bundle

### PR DESCRIPTION
**Pull request by seibtph**

### CODE REVIEW

**Review by MDevster — APPROVED** [review]

**Comment by Toflar** [comment]
You merged with spelling mistakes, please provide a PR to fix those ;)

**Comment by seibtph** [comment]
@Toflar Which spelling mistakes do you mean?

**Comment by Toflar** [comment]
There were issues and @MDevster merged without having them fixed. Not your fault. You don't have to do anything.
Unfortunately, GitHub does not support jobs that display a warning - they can only fail or pass. People said that our spell checker prevented them from contributing if it fails which is why I configured it in a way that it allows to fail and expect the ones having merge permissions on this repo to check those before they merge. But that did not happen, so I guess I have to go back to a hard failing CI...

**Comment by fritzmg** [comment]
I am also in favor of going back to hard failing. The current way is more annoying, because:

* You always have to check manually after each commit, even when everything is correct (as you won't know without checking).
* It requires scrolling and more clicks to see what needs to be fixed.

**Comment by Toflar** [comment]
See https://github.com/contao/package-metadata/pull/449

**Pull request merged**
