### PR TITLE
update lasr theme description

### PR DESCRIPTION
**Pull request by denniserdmann**

### CODE REVIEW

**Comment by denniserdmann** [comment]
@xchs i don't know why, but every PR is automatically assigned to richard and i can't change that.

**Comment by zoglo** [comment]
@denniserdmann 

https://github.com/contao/package-metadata/blob/3a1a6e3ad1d70bcf6e5fbb7e12a370e5d0955da8/CODEOWNERS#L25C1-L25C48

you could change that here

**Review by xchs — DISMISSED** [review]

**Review by xchs — APPROVED** [review]

**Comment by denniserdmann** [comment]
removed richard, but still can not remove him as reviewer for this pr

**Comment by xchs** [comment]
> removed richard, but still can not remove him as reviewer for this pr

@denniserdmann Unfortunately, I can't either. :confused:

**Comment by richardhj** [comment]
Must become merged for sure :-)

**Review by richardhj — APPROVED** [review]

**Pull request merged**
