### PR TITLE
Add logo for vendor qbus

### PR DESCRIPTION
**Pull request by gmpf**

### CODE REVIEW

**Comment by xchs** [comment]
Would you mind to make the SVG logo square?

**Comment by fritzmg** [comment]
Other logos aren't square either, I don't think it is a requirement?

**Comment by gmpf** [comment]
There is only a problem if the logo is taller than it is wide (portrait) because of the `max-height: 100%;` in:
```
.discover-package__icon img {
    width: 100%;
    height: auto;
    max-height: 100%;
}
```
– https://github.com/contao/package-list/blob/master/src/components/fragments/DiscoverPackage.vue#L88-L92

The logo file in this PR is in landscape, so no problems there.

I noticed you can actually see the portrait problem in action here:
https://github.com/contao/package-metadata/blob/master/meta/hofff/logo.svg
vs.
https://extensions.contao.org/?q=hofff&pages=1
Nudge @frontendschlampe and/or @aschempp depending on which end this is supposed to be resolved. ;)

IMHO, the easiest way is to ditch the `` for `background-image`:
```
<figure class="discover-package__icon" style="background-image:(path/to/logo.svg)">
</figure>

.discover-package__icon {
  […]
  background-repeat: no-repeat;
  background-size: contain;
  background-position: center;
}
```

**Comment by fritzmg** [comment]
> IMHO, the easiest way is to ditch the `` for `background-image`:

That wouldn't be semantically correct ;). No need for a background-image approach... we have `object-fit` nowadays, or `flex` or even the good old

```css
figure {
    position: relative;
    height: 0;
    padding-top: 100%;
}

figure img {
    display: block;
    width: auto;
    height: auto;
    max-width: 100%;
    max-height: 100%;
    position: absolute;
    left: 0; right: 0; top: 0; bottom: 0;
    margin: auto;
}
```

**Pull request merged**
