### PR TITLE
Remove the codefog/isotope_stock_management

### PR DESCRIPTION
**Pull request by qzminski**

### CODE REVIEW

**Comment by fritzmg** [comment]
Presumably this extension still exists in Contao instances? If so, I don't think we should remove the meta data.

**Comment by aschempp** [comment]
not sure we support deprecations through metadata 🤔

**Comment by aschempp** [comment]
@qzminski can you try setting the "discoverable" to false?

docs/en/README.md

**Comment by qzminski** [comment]
@aschempp done.

**Review by aschempp — APPROVED** [review]

**Pull request merged**
