### PR TITLE
fix title of trilobit-gmbh/contao-formvalidation-bundle

### PR DESCRIPTION
**Pull request by trilobit-gmbh**

### CODE REVIEW

**Comment by Toflar** [comment]
Needs fixes.

**Comment by trilobit-gmbh** [comment]
Add "Formvalidation" to the whitelist (de); [https://github.com/contao/package-metadata/pull/110](url)

**Comment by Toflar** [comment]
Sorry but can you please update the PR and not just create new ones? They belong together and also have to be tested agains spelling mistakes together. I only merge a PR if it fulfils all checks so even if I would merge the other PR, this one would still not be ready because it would need at least a rebase.

**Comment by Toflar** [comment]
Thank you :)

**Pull request merged**
