### PR TITLE
Netzhirsch Contao Slider Bundle

### PR DESCRIPTION
**Pull request by luhmannAlexander**
The Contao Slider Bundle was developed to provide web developers and designers with a powerful tool to seamlessly integrate attractive sliders and presentations into their Contao projects. With a variety of features and customization options, the bundle allows flexible and creative design of slider elements to capture visitors' attention and improve user experience.

### CODE REVIEW

**Review by xchs — APPROVED** [review]

**Comment by xchs** [comment]
@luhmannAlexander Could you please fix the remaining errors: https://github.com/contao/package-metadata/actions/runs/7623166913/job/20781922096?pr=530

**Review by xchs — APPROVED** [review]

**Comment by xchs** [comment]
@luhmannAlexander For what reason did you remove almost the entire description of the extension?

**Comment by luhmannAlexander** [comment]
Unfortunately, I couldn't figure out how to configure the spell checker. For me it doesn't seem to allow umlauts and the defaults are probably not loaded either. I installed the linter in my ubuntu:22.04 docker and with php lint /var/www/html/package-metadata/meta/netzhirsch/contao-slider-bundle/de.yml executed.

 [ERROR] [Package: netzhirsch/contao-slider-bundle; Language: de]: Property "title" does not pass the spell checker.    
         Either update the allow list or fix the spelling :) Errors: Netzhirsch, Contao, Slider, Bundle                 
                                                                                                                        

                                                                                                                        
 [ERROR] [Package: netzhirsch/contao-slider-bundle; Language: de]: Property "description" does not pass the spell       
         checker. Either update the allow list or fix the spelling :) Errors: Contao, Slider, Bundle, Webentwicklern,   
         m�, chtiges, Verf�, gung, Slider, Pr�, sentationen, Contao, Anpassungsoptionen, erm�, Bundle, Slider,          
         Benutzererfahrung

**Comment by xchs** [comment]
@luhmannAlexander It would actually be sufficient if you just add the mentioned words to the allowlist list: https://github.com/contao/package-metadata/blob/main/linter/allowlists/de.txt

image

**Pull request merged**
